// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pedidos.Infraestructura.Context;

#nullable disable

namespace Pedidos.Infraestructura.Migrations
{
    [DbContext(typeof(PedidosDbContext))]
    partial class OrdenesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pedidos.Infraestructura.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCliente")
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Pedidos.Infraestructura.Entities.PedidoCola", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PedidoId");

                    b.ToTable("PedidoCola");
                });

            modelBuilder.Entity("Pedidos.Infraestructura.Entities.PedidoProcesado", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaProcesamiento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PedidoId");

                    b.ToTable("PedidosProcesados");
                });

            modelBuilder.Entity("Pedidos.Infraestructura.Entities.Stock", b =>
                {
                    b.Property<string>("Sku")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("Sku");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Sku = "SKU001",
                            Cantidad = 100
                        },
                        new
                        {
                            Sku = "SKU002",
                            Cantidad = 50
                        },
                        new
                        {
                            Sku = "SKU003",
                            Cantidad = 75
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
